# Generated by Django 5.2.15 on 2026-06-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tension_arterielle', models.CharField(max_length=20)),
                ('rythme_cardiaque', models.PositiveIntegerField()),
                ('frequence_respiratoire', models.PositiveIntegerField()),
                ('saturation_oxygene', models.PositiveIntegerField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='consultations.consultation')),
            ],
        ),
    ]
