# Generated by Django 5.2.15 on 2026-06-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constantes', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constante',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constante', to='consultations.consultation'),
        ),
    ]
