# Generated by Django 5.2.15 on 2026-06-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('prochaine_visite', models.DateField(blank=True, null=True)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='rendezvous.rendezvous')),
            ],
        ),
    ]
