# Generated by Django 5.2.15 on 2026-06-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.BooleanField(default=False)),
                ('allergies_details', models.TextField(blank=True)),
                ('maladies_chroniques', models.BooleanField(default=False)),
                ('maladies_details', models.TextField(blank=True)),
                ('prend_medicaments', models.BooleanField(default=False)),
                ('medicaments_details', models.TextField(blank=True)),
                ('operations', models.BooleanField(default=False)),
                ('operations_details', models.TextField(blank=True)),
                ('fumeur', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='patients.patient')),
            ],
        ),
    ]
