# Generated by Django 5.2.15 on 2026-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('nombre_patients', models.PositiveIntegerField(default=0)),
                ('nombre_medecins', models.PositiveIntegerField(default=0)),
                ('nombre_rendezvous', models.PositiveIntegerField(default=0)),
                ('nombre_consultations', models.PositiveIntegerField(default=0)),
                ('nombre_ordonnances', models.PositiveIntegerField(default=0)),
                ('revenu_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
    ]
